function html = mdoc_render(info)
% mdoc_render  Render parsed documentation info as a self-contained HTML page.
%
% html = mdoc_render(info) takes the struct returned by mdoc_parse and
% generates a complete HTML string styled to approximate MATLAB doc pages.
% Markdown rendering is handled client-side by marked.js, with highlight.js
% for code blocks and KaTeX for LaTeX math.

arguments
    info (1,1) struct
end

parts = {};
parts{end+1} = htmlHead(info.Name);
parts{end+1} = '<body><div class="doc-page">';

% Title and synopsis
parts{end+1} = sprintf('<h1 class="func-name">%s</h1>', htmlEscape(info.Name));
if info.Synopsis ~= ""
    parts{end+1} = sprintf('<p class="synopsis">%s</p>', htmlEscape(info.Synopsis));
end

% Syntax
parts{end+1} = renderSyntax(info);

% Description
if info.Description ~= ""
    parts{end+1} = '<h2>Description</h2>';
    parts{end+1} = markdownDiv(info.Description);
end

% Input Arguments
if ~isempty(info.InputArgs)
    parts{end+1} = '<h2>Input Arguments</h2>';
    parts{end+1} = renderArguments(info.InputArgs);
end

% Name-Value Arguments
if ~isempty(info.NameValueArgs)
    parts{end+1} = '<h2>Name-Value Arguments</h2>';
    parts{end+1} = '<p>Specify optional pairs of arguments as <code>Name1=Value1,...,NameN=ValueN</code>.</p>';
    parts{end+1} = renderArguments(info.NameValueArgs);
end

% Output Arguments
if ~isempty(info.OutputArgs)
    parts{end+1} = '<h2>Output Arguments</h2>';
    parts{end+1} = renderOutputArguments(info.OutputArgs);
end

% Remaining sections in spec order
sectionOrder = ["Examples", "Tips", "Algorithms", "Version History", ...
    "References", "More About"];
for s = sectionOrder
    content = findSectionContent(info.Sections, s);
    if content ~= ""
        parts{end+1} = sprintf('<h2>%s</h2>', htmlEscape(s)); %#ok<AGROW>
        parts{end+1} = markdownDiv(content); %#ok<AGROW>
    end
end

% See Also
if ~isempty(info.SeeAlso)
    parts{end+1} = '<h2>See Also</h2>';
    links = {};
    for k = 1:numel(info.SeeAlso)
        name = strtrim(info.SeeAlso(k));
        links{k} = sprintf('<a href="matlab:mdoc(''%s'')">%s</a>', ...
            htmlEscape(name), htmlEscape(name));
    end
    parts{end+1} = sprintf('<p>%s</p>', strjoin(string(links), " | "));
end

parts{end+1} = '</div>';
parts{end+1} = renderScript();
parts{end+1} = '</body></html>';

html = strjoin(string(parts), newline);
end

%% ---- Local Functions ----

function s = htmlHead(funcName)
s = sprintf([...
    '<!DOCTYPE html>\n' ...
    '<html lang="en">\n' ...
    '<head>\n' ...
    '<meta charset="UTF-8">\n' ...
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n' ...
    '<title>%s — Documentation</title>\n' ...
    '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">\n' ...
    '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/github.min.css">\n' ...
    '<style>\n%s</style>\n' ...
    '</head>'], htmlEscape(funcName), cssStyles());
end

function css = cssStyles()
css = [...
    ':root {' newline ...
    '  --blue: #0076a8;' newline ...
    '  --dark-blue: #00547a;' newline ...
    '  --light-bg: #f7f7f7;' newline ...
    '  --border: #e0e0e0;' newline ...
    '  --text: #333;' newline ...
    '  --code-bg: #f4f4f4;' newline ...
    '}' newline ...
    'body {' newline ...
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;' newline ...
    '  color: var(--text);' newline ...
    '  line-height: 1.6;' newline ...
    '  margin: 0;' newline ...
    '  padding: 0;' newline ...
    '}' newline ...
    '.doc-page {' newline ...
    '  max-width: 900px;' newline ...
    '  margin: 0 auto;' newline ...
    '  padding: 24px 32px;' newline ...
    '}' newline ...
    'h1.func-name {' newline ...
    '  color: var(--dark-blue);' newline ...
    '  font-size: 1.8em;' newline ...
    '  border-bottom: 2px solid var(--blue);' newline ...
    '  padding-bottom: 8px;' newline ...
    '  margin-bottom: 4px;' newline ...
    '}' newline ...
    'p.synopsis {' newline ...
    '  font-size: 1.1em;' newline ...
    '  color: #555;' newline ...
    '  margin-top: 0;' newline ...
    '  margin-bottom: 24px;' newline ...
    '}' newline ...
    'h2 {' newline ...
    '  color: var(--dark-blue);' newline ...
    '  font-size: 1.3em;' newline ...
    '  margin-top: 32px;' newline ...
    '  border-bottom: 1px solid var(--border);' newline ...
    '  padding-bottom: 6px;' newline ...
    '}' newline ...
    'h3 { color: var(--dark-blue); font-size: 1.1em; }' newline ...
    '.syntax-block {' newline ...
    '  background: var(--light-bg);' newline ...
    '  border: 1px solid var(--border);' newline ...
    '  border-radius: 4px;' newline ...
    '  padding: 12px 16px;' newline ...
    '  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;' newline ...
    '  font-size: 0.9em;' newline ...
    '  overflow-x: auto;' newline ...
    '}' newline ...
    '.arg-entry {' newline ...
    '  background: var(--light-bg);' newline ...
    '  border: 1px solid var(--border);' newline ...
    '  border-radius: 4px;' newline ...
    '  margin: 12px 0;' newline ...
    '  padding: 12px 16px;' newline ...
    '}' newline ...
    '.arg-header {' newline ...
    '  display: flex;' newline ...
    '  justify-content: space-between;' newline ...
    '  align-items: baseline;' newline ...
    '  flex-wrap: wrap;' newline ...
    '  gap: 8px;' newline ...
    '}' newline ...
    '.arg-name {' newline ...
    '  font-family: monospace;' newline ...
    '  font-weight: bold;' newline ...
    '  font-size: 1.05em;' newline ...
    '  color: var(--dark-blue);' newline ...
    '}' newline ...
    '.arg-meta {' newline ...
    '  font-size: 0.85em;' newline ...
    '  color: #666;' newline ...
    '}' newline ...
    '.arg-desc {' newline ...
    '  margin-top: 8px;' newline ...
    '}' newline ...
    'pre { margin: 8px 0; }' newline ...
    'pre code {' newline ...
    '  background: var(--code-bg);' newline ...
    '  display: block;' newline ...
    '  padding: 12px;' newline ...
    '  border-radius: 4px;' newline ...
    '  overflow-x: auto;' newline ...
    '}' newline ...
    'code {' newline ...
    '  background: var(--code-bg);' newline ...
    '  padding: 1px 4px;' newline ...
    '  border-radius: 3px;' newline ...
    '  font-size: 0.9em;' newline ...
    '}' newline ...
    'pre code { padding: 12px; font-size: 0.9em; }' newline ...
    '.callout {' newline ...
    '  border-left: 4px solid;' newline ...
    '  padding: 12px 16px;' newline ...
    '  margin: 12px 0;' newline ...
    '  border-radius: 0 4px 4px 0;' newline ...
    '}' newline ...
    '.callout-note { border-color: #0076a8; background: #e8f4f8; }' newline ...
    '.callout-warning { border-color: #e6a800; background: #fff8e1; }' newline ...
    '.callout-important { border-color: #d32f2f; background: #fde8e8; }' newline ...
    '.callout-title {' newline ...
    '  font-weight: bold;' newline ...
    '  margin-bottom: 4px;' newline ...
    '}' newline ...
    '.see-also a {' newline ...
    '  color: var(--blue);' newline ...
    '  text-decoration: none;' newline ...
    '}' newline ...
    '.see-also a:hover { text-decoration: underline; }' newline ...
    ];
end

function s = renderSyntax(info)
% Render syntax section from function signature
s = '<h2>Syntax</h2><div class="syntax-block"><pre>';
for k = 1:numel(info.Signature)
    sig = info.Signature{k};
    % Strip 'function ' prefix for display
    display = regexprep(sig, '^function\s+', '');
    s = s + htmlEscape(string(display));
    if k < numel(info.Signature)
        s = s + newline;
    end
end
s = s + "</pre></div>";
end

function s = renderArguments(args)
% Render input or name-value arguments as styled cards
parts = {};
for k = 1:numel(args)
    a = args(k);
    parts{end+1} = '<div class="arg-entry">'; %#ok<AGROW>
    parts{end+1} = '<div class="arg-header">'; %#ok<AGROW>
    parts{end+1} = sprintf('<span class="arg-name">%s</span>', htmlEscape(a.Name)); %#ok<AGROW>

    % Build meta string: size, class, default
    meta = {};
    if a.Size ~= ""
        meta{end+1} = char(a.Size);
    end
    if a.Class ~= ""
        meta{end+1} = char(a.Class);
    end
    if a.Default ~= ""
        meta{end+1} = "default: " + a.Default;
    end
    if ~isempty(meta)
        parts{end+1} = sprintf('<span class="arg-meta">%s</span>', ...
            htmlEscape(strjoin(string(meta), " · "))); %#ok<AGROW>
    end
    parts{end+1} = '</div>'; %#ok<AGROW>

    % Description: prefer long desc, fall back to short desc
    desc = a.ShortDesc;
    if isfield(a, 'LongDesc') && a.LongDesc ~= ""
        desc = a.LongDesc;
    end
    if desc ~= ""
        parts{end+1} = '<div class="arg-desc">'; %#ok<AGROW>
        parts{end+1} = markdownDiv(desc); %#ok<AGROW>
        parts{end+1} = '</div>'; %#ok<AGROW>
    end
    parts{end+1} = '</div>'; %#ok<AGROW>
end
s = strjoin(string(parts), newline);
end

function s = renderOutputArguments(outArgs)
parts = {};
for k = 1:numel(outArgs)
    a = outArgs(k);
    parts{end+1} = '<div class="arg-entry">'; %#ok<AGROW>
    parts{end+1} = sprintf('<div class="arg-header"><span class="arg-name">%s</span></div>', ...
        htmlEscape(a.Name)); %#ok<AGROW>
    if a.LongDesc ~= ""
        parts{end+1} = '<div class="arg-desc">'; %#ok<AGROW>
        parts{end+1} = markdownDiv(a.LongDesc); %#ok<AGROW>
        parts{end+1} = '</div>'; %#ok<AGROW>
    end
    parts{end+1} = '</div>'; %#ok<AGROW>
end
s = strjoin(string(parts), newline);
end

function content = findSectionContent(sections, heading)
% Find a section by heading name
content = "";
for k = 1:numel(sections)
    if sections(k).Heading == heading
        content = string(sections(k).Content);
        return
    end
end
end

function s = markdownDiv(text)
% Wrap raw markdown text in a div for client-side rendering by marked.js
% We use a script tag (type text/markdown) to avoid HTML parsing issues
escaped = strrep(text, "</script", "<\/script");  % Escape for safety
s = sprintf('<div class="md-content"><script type="text/markdown">%s</script></div>', escaped);
end

function s = htmlEscape(text)
text = string(text);
text = strrep(text, "&", "&amp;");
text = strrep(text, "<", "&lt;");
text = strrep(text, ">", "&gt;");
text = strrep(text, '"', "&quot;");
s = text;
end

function s = renderScript()
s = [...
    '<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>' newline ...
    '<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/highlight.min.js"></script>' newline ...
    '<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/languages/matlab.min.js"></script>' newline ...
    '<script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>' newline ...
    '<script>' newline ...
    'document.addEventListener("DOMContentLoaded", function() {' newline ...
    '  // Configure marked' newline ...
    '  marked.setOptions({' newline ...
    '    highlight: function(code, lang) {' newline ...
    '      if (lang && hljs.getLanguage(lang)) {' newline ...
    '        return hljs.highlight(code, {language: lang}).value;' newline ...
    '      }' newline ...
    '      return hljs.highlight(code, {language: "matlab"}).value;' newline ...
    '    },' newline ...
    '    gfm: true,' newline ...
    '    breaks: false' newline ...
    '  });' newline newline ...
    '  // Render all markdown content divs' newline ...
    '  document.querySelectorAll(".md-content").forEach(function(div) {' newline ...
    '    var scriptTag = div.querySelector("script[type=\"text/markdown\"]");' newline ...
    '    if (scriptTag) {' newline ...
    '      var md = scriptTag.textContent;' newline ...
    '      // Handle callouts: > [!NOTE], > [!WARNING], > [!IMPORTANT]' newline ...
    '      md = md.replace(/^>\s*\[!(NOTE|WARNING|IMPORTANT)\]\s*\n((?:^>.*\n?)*)/gm, function(match, type, body) {' newline ...
    '        var cleanBody = body.replace(/^>\s?/gm, "");' newline ...
    '        return "<div class=\"callout callout-" + type.toLowerCase() + "\"><div class=\"callout-title\">" + type + "</div>" + cleanBody + "</div>\n";' newline ...
    '      });' newline ...
    '      div.innerHTML = marked.parse(md);' newline ...
    '    }' newline ...
    '  });' newline newline ...
    '  // Render KaTeX math' newline ...
    '  function renderMath(el) {' newline ...
    '    var html = el.innerHTML;' newline ...
    '    // Display math: $$...$$' newline ...
    '    html = html.replace(/\$\$([^$]+?)\$\$/g, function(match, tex) {' newline ...
    '      try { return katex.renderToString(tex, {displayMode: true}); }' newline ...
    '      catch(e) { return match; }' newline ...
    '    });' newline ...
    '    // Inline math: $...$' newline ...
    '    html = html.replace(/\$([^$]+?)\$/g, function(match, tex) {' newline ...
    '      try { return katex.renderToString(tex, {displayMode: false}); }' newline ...
    '      catch(e) { return match; }' newline ...
    '    });' newline ...
    '    el.innerHTML = html;' newline ...
    '  }' newline ...
    '  document.querySelectorAll(".md-content").forEach(renderMath);' newline ...
    '});' newline ...
    '</script>'];
end
